#99 Refactor Spring Security Refactor
moaydogdu/StockManagementStudyCase pull request #100
Opened 2024-01-21 21:26 UTC by mehmetseymusyuzen

2024-01-22 19:30 UTC, moaydogdu requested changes

2024-01-22 19:30 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/security/controller/AuthenticationController.java
> +                .refreshToken(refreshTokenRequest);
Bu metoda daha iyi bir isimlendirme gerekiyor.

2024-01-22 19:30 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/security/repository/UserRepository.java
> +    boolean existsUserEntitiesByEmail(
existUserEntityByEmail daha verimli bir fonksiyon olabilir.

2024-01-22 19:30 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/security/service/AuthenticationService.java
> +                .toAuthenticationResponse(tokenService.generateToken(userEntity));
Bu kısımları parçalı yazalım.

2024-01-22 19:30 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/security/service/UserService.java
> +    public User getUserByUsername(String email) throws UsernameNotFoundException {
Bu kısmı email olarak isimlendirebiliriz. getUserByEmail

2024-01-22 19:30 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/security/model/dto/response/GenerateTokenResponse.java
> +public class GenerateTokenResponse {
Bu bir response olarak isimlendirilmemeli. Belki AccessAndRefreshToken adında bir domain model olarak kullanılabilir.

2024-01-22 19:57 UTC, anilhazar approved these changes

2024-01-24 00:53 UTC, moaydogdu approved these changes

2024-01-24 00:54 UTC, merged