create getById endpoint for warehouse
moaydogdu/StockManagementStudyCase pull request #25
Opened 2023-11-20 18:05 UTC by Harun170518513

2023-11-20 19:58 UTC, mehmetseymusyuzen requested changes

2023-11-20 19:58 UTC, mehmetseymusyuzen commented on src/main/java/com/study/stockmanagementstudycase/controller/WareHouseController.java
> +    @GetMapping("/{id}")
`@GetMapping("/{id}")` bu kismi su sekilde degistirelim `@GetMapping("/{wareHouseId}")`

2023-11-20 19:58 UTC, mehmetseymusyuzen commented on src/main/java/com/study/stockmanagementstudycase/controller/WareHouseController.java
> +    public ResponseEntity<WareHouseResponse> getUserById(@PathVariable String id){
`getUserById(@PathVariable String id)` bu kisimda Stringin onune final ekleyelim ve id isimlendirilmesini degistirelim ve PathVariable'dan sonra bunu ekleyelim wareHouseId  `getUserById(@PathVariable("wareHouseId") final String wareHouseId){`

2023-11-20 19:58 UTC, mehmetseymusyuzen commented on src/main/java/com/study/stockmanagementstudycase/controller/WareHouseController.java
> +        return ResponseEntity.ok(WareHouseDtoMapper.toGetResponse( wareHouseService.getWareHouseById(id)));
Butun islemleri ok icerisinde yapmak yerine bu sekilde yapabiliriz
```
final WareHouse wareHouse = 
wareHouseService.getWareHouseById(wareHouseId));
final WareHouseResponse wareHouseResponse = WareHouseDtoMapper.toGetResponse(wareHouse);
return ResponseEntity.ok(wareHouseResponse).build();
```

2023-11-20 19:58 UTC, mehmetseymusyuzen commented on src/main/java/com/study/stockmanagementstudycase/service/WareHouseService.java
> +    WareHouse getWareHouseById( String id);
final ekleyecegiz ve id daha spesifik halde yazilmali "wareHouseId"

2023-11-20 19:58 UTC, mehmetseymusyuzen commented on src/main/java/com/study/stockmanagementstudycase/service/impl/WareHouseServiceImpl.java
> +    public WareHouse getWareHouseById(String id) {
parametreyi final alalim ve ismini "wareHouseId" olarak guncelleyelim

2023-11-20 19:58 UTC, mehmetseymusyuzen commented on src/main/java/com/study/stockmanagementstudycase/service/impl/WareHouseServiceImpl.java
> +    }
Optinal nesne almak yerine bu islemi orElseThrow metodu ile kullanarak yapabiliriz

2023-11-21 17:15 UTC, moaydogdu requested changes

2023-11-21 17:15 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/controller/WareHouseController.java
> +    public ResponseEntity<WareHouseResponse> getUserById(@PathVariable("wareHouseId") final String wareHouseId){
Metod isimlendirmesi hatalı, getUserById değil getWareHouseById olmalıydı. Burada User dönmüyoruz, WareHouse dönüyoruz.

2023-11-21 17:15 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/impl/WareHouseServiceImpl.java
> +        WareHouseEntity wareHouseEntity1 = wareHouseEntity.orElseThrow(()->new RuntimeException("WareHouse cant find given id"));
İkinci bir nesne tanımlamaya gerek yok, nesneyi optional tanımlamaya da gerek yok. Dönüşü optional olan bir nesneyi .get() metodu ile almak yerine .orElseThrow() metodu ile alabiliriz. NullPointer gibi bir hata yakalanınca da belirttiğimiz hata fırlatılır. 
Diğer servis metotları metodlarında bu kullanım ile ilgili örnek zaten var.

2023-11-21 17:15 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/impl/WareHouseServiceImpl.java
> +}}
Burada peş peşe iki süslü parantez kullanmak yerine doğru sıralama ve hizalama ile kullanalım. Ayrıca classın sonuna bir satır boşluk ekleyelim.

2023-11-21 17:16 UTC, moaydogdu commented
Ayrıca bir reviewdeki request changeleri hallettiğimizde resolve conversation diyerek kapatalım.

2023-11-21 17:24 UTC, moaydogdu commented
Commit atarken Türkçe değil İngilizce ve commit standartlarında commit atalım.

Örneğin "Bütün hatalar duzeltildi" yerine "Refactor requested changes" yazalım.

2023-11-21 19:07 UTC, moaydogdu approved these changes
LGTM!

2023-11-21 19:15 UTC, mehmetseymusyuzen approved these changes

2023-11-21 19:28 UTC, merged