Create WareHouseNotFoundException and Refactor Related Classes
moaydogdu/StockManagementStudyCase pull request #42
Opened 2023-11-26 01:34 UTC by mehmetseymusyuzen

2023-11-26 01:41 UTC, moaydogdu requested changes

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/StockNotFoundException.java
> +@ResponseStatus(HttpStatus.NOT_FOUND)
Burada ResponseStatus kullanmamalıyız.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/StockNotFoundException.java
> +    private static final long serialVersionUID = -7067959181502070423L;
Bütün exception sınıflarında aynı serialVersionUID kullanılmış, her biri unique olmalı.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/StockNotFoundException.java
> +    }
Bu constructor mesaj belirtmeyi zorunlu kılıyor. İkinci bir parametresiz constructor yazıp varsayılan mesaj ile kullanıma izin vermeliyiz.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseEntityNotFoundException.java
> +    }
Bu constructor mesaj belirtmeyi zorunlu kılıyor. İkinci bir parametresiz constructor yazıp varsayılan mesaj ile kullanıma izin vermeliyiz.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseEntityNotFoundException.java
> +public class WareHouseEntityNotFoundException extends RuntimeException implements Serializable {
Serializable implementasyonuna ihtiyaç yok.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseNameAndAddressAlreadyExistException.java
> +    }
Bu constructor mesaj belirtmeyi zorunlu kılıyor. İkinci bir parametresiz constructor yazıp varsayılan mesaj ile kullanıma izin vermeliyiz.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseNameAndAddressAlreadyExistException.java
> +public class WareHouseNameAndAddressAlreadyExistException extends RuntimeException implements Serializable {
Serializable implementasyonuna ihtiyaç yok.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseNotFoundException.java
> +    }
Bu constructor mesaj belirtmeyi zorunlu kılıyor. İkinci bir parametresiz constructor yazıp varsayılan mesaj ile kullanıma izin vermeliyiz.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseEntityNotFoundException.java
> +            "The specified WareHouseEntity is not found!";
Burada WareHouseEntity değil WareHouse olarak belirtelim, bu exception'un mesajını doğrudan response olarak dönmek istersek daha anlamlı olabilir.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseEntityNotFoundException.java
> +    private static final long serialVersionUID = -7067959181502070423L;
Bütün exception sınıflarında aynı serialVersionUID kullanılmış, her biri unique olmalı.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseNameAndAddressAlreadyExistException.java
> +    private static final long serialVersionUID = -7067959181502070423L;
Bütün exception sınıflarında aynı serialVersionUID kullanılmış, her biri unique olmalı.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseNotFoundException.java
> +    private static final long serialVersionUID = -7067959181502070423L;
Bütün exception sınıflarında aynı serialVersionUID kullanılmış, her biri unique olmalı.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouse/impl/WareHouseDeleteServiceImpl.java
> +                .orElseThrow(() -> new WareHouseNotFoundException("WareHouse not found"));
Default mesajda zaten aynı ifade var, mesaj olmaksızın constructor çağıralım. Ekstra bir durum yok çünkü.

2023-11-26 01:41 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouse/impl/WareHouseServiceImpl.java
> +                .orElseThrow(() -> new WareHouseNotFoundException("WareHouse can not find given id"));
Belirtilen mesaja gerek yok, zaten sınıfın içindeki mesajda bu ifade var. Parametresiz bir constructor kullanalım ekstra bir mesajımız yoksa.

2023-11-26 08:05 UTC, mehmetseymusyuzen commented
Gelistirme halen devam edecek. Lutfen mergelemeyin.

2023-11-28 21:03 UTC, moaydogdu requested changes

2023-11-28 21:03 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseEntityNotFoundException.java
> +public class WareHouseEntityNotFoundException extends RuntimeException{
Bu kısımda isimlendirmede değişikliğe gidebiliriz.

WareHouseNotFoundException diyebiliriz.

2023-11-28 21:03 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/stock/impl/StockPurchaseServiceImpl.java
> +                .orElseThrow(() -> new StockNotFoundException());
Burada lambda kullanmak yerine method reference kullanılabilir.

2023-11-28 21:03 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/common/exception/WareHouseNameAndAddressAlreadyExistException.java
> +public class WareHouseNameAndAddressAlreadyExistException extends RuntimeException{
Burada class ismini "WareHouseAlreadyExistException" yapabiliriz.

2023-11-28 21:03 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/stock/impl/StockPurchaseServiceImpl.java
> +                .orElseThrow(() -> new StockNotFoundException());
StockNotFoundException::new

2023-11-28 21:03 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouse/impl/WareHouseCreateServiceImpl.java
>          if (wareHouseRepository.existsWareHouseEntitiesByNameAndAddress(name, address)) {
Boolean.TRUE.equals(koşul) şeklinde kullanırsak, daha okunabilir bir hale gelebilir.

2023-11-28 21:03 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouse/impl/WareHouseDeleteServiceImpl.java
> +                .orElseThrow(() -> new WareHouseNotFoundException());
Method reference kullanalım ekstra bir parametremiz yoksa.

2023-11-28 21:03 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouse/impl/WareHouseServiceImpl.java
> +                .orElseThrow(() -> new WareHouseNotFoundException());
Method reference kullanalım ekstra bir parametremiz yoksa.

2023-11-28 21:03 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouse/impl/WareHouseUpdateServiceImpl.java
> +                .orElseThrow(() -> new WareHouseEntityNotFoundException());
Method reference kullanalım ekstra bir parametremiz yoksa.

2023-11-28 21:03 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouse/impl/WareHouseUpdateServiceImpl.java
>          if (wareHouseRepository.existsWareHouseEntitiesByNameAndAddress(name, address)) {
Boolean.TRUE.equals(koşul) bu şekilde kullanırsak daha okunabilir bir hal alabilir.

2023-11-28 21:03 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouseStock/impl/WareHouseStockUpdateServiceImpl.java
> +                .orElseThrow(() -> new WareHouseStockNotFoundException());
Method reference kullanalım ekstra bir parametremiz yoksa.

2023-11-28 21:24 UTC, moaydogdu requested changes

2023-11-28 21:24 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouse/impl/WareHouseUpdateServiceImpl.java
> +                .orElseThrow(() -> new WareHouseEntityNotFoundException());
Method reference kullanalım.

2023-11-28 21:39 UTC, moaydogdu approved these changes
LGTM!

2023-11-28 21:40 UTC, merged