#50 WareHouseStockService
moaydogdu/StockManagementStudyCase pull request #60
Opened 2023-12-11 21:11 UTC by mehmetseymusyuzen

2023-12-11 21:14 UTC, artfulCoder98 approved these changes
LGTM:D

2023-12-11 21:15 UTC, moaydogdu requested changes

2023-12-11 21:15 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouseStock/WareHouseStockService.java
> +    WareHouseStock getWareHouseStockById(final String wareHouseStockId);
parametreyi almadan önce bir alt satıra inelim, şöyle ki:

```
WareHouseStock getWareHouseStockById(
        final String wareHouseStockId
);
```

2023-12-11 21:15 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/service/wareHouseStock/impl/WareHouseStockServiceImpl.java
> +        final List<WareHouseStockEntity> wareHouseStockEntityList = wareHouseStockRepository
wareHouseStockEntityList yerine wareHouseStockEntitiesFromDb şeklinde isimlendirebiliriz.

2023-12-11 21:15 UTC, moaydogdu commented on src/test/java/com/study/stockmanagementstudycase/service/wareHouseStock/impl/WareHouseStockServiceImplTest.java
> +        //Assert
//Assert şeklinde belirtmemize gerek yok, Then kısmı zaten assertionları içeren kısım.

2023-12-11 21:15 UTC, moaydogdu commented on src/test/java/com/study/stockmanagementstudycase/service/wareHouseStock/impl/WareHouseStockServiceImplTest.java
> +
Boşluğu alalım.

2023-12-12 18:58 UTC, moaydogdu approved these changes
LGTM!

2023-12-12 18:59 UTC, merged