#72 Refactor WareHouseController.java --> Returning the warehouseId when warehouse creation is complete
moaydogdu/StockManagementStudyCase pull request #82
Opened 2024-01-02 00:57 UTC by mehmetseymusyuzen

…warehouse creation is complete

2024-01-02 05:29 UTC, moaydogdu requested changes

2024-01-02 05:29 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/controller/WareHouseController.java
> +        return ResponseEntity.ok("WareHouse Id : " + wareHouse.getId());
"WareHouse Id : " şeklinde belirtmemize gerek yok, doğrudan id değerini dönebiliriz.

2024-01-02 10:35 UTC, mehmetseymusyuzen commented on src/main/java/com/study/stockmanagementstudycase/controller/WareHouseController.java
> +        return ResponseEntity.ok("WareHouse Id : " + wareHouse.getId());
WareHouse id -> id olarak degistirdim en azindan create islemi sonrasinda donen degerin ne oldugu hakkinda bilgi sahibi olmamizin daha iyi olacagini dusunuyorum ama karar yine sizin.

2024-01-02 12:59 UTC, moaydogdu requested changes

2024-01-02 12:59 UTC, moaydogdu commented on src/main/java/com/study/stockmanagementstudycase/controller/WareHouseController.java
> +        return ResponseEntity.ok("id : " + wareHouse.getId());
Bu kısımda id değerini doğrudan dönelim. Buradaki amaç Postman üzerinde düzgün görmekten ziyade bir frontend tarafında dönen verinin doğrudan kullanılabilmesi. Aksi halde döndüğümüz string değerde concat gibi bir işlem gerekecek, ilerleyen süreçte burada bir değişiklik yapsak, frontend tarafını da buna mecbur bırakırız. 

Bu sebeple doğrudan değeri dönmek çok daha mantıklı. Böylece bağımlılığı da minimuma indirebiliriz.

2024-01-03 15:28 UTC, mehmetseymusyuzen commented on src/main/java/com/study/stockmanagementstudycase/controller/WareHouseController.java
> +        return ResponseEntity.ok("id : " + wareHouse.getId());
tamamdir istedigin gibi degisiklikleri yaptim

2024-01-03 18:11 UTC, moaydogdu approved these changes
LGTM!

2024-01-03 18:11 UTC, merged